### ISSUE TITLE
Panel 004-onboardingmentoring checklist

### ISSUE THREAD

**Issue by bernhold** [ideas-productivity/remote-work-panels#2]
**Preparing to advertise panel**
- Collect initial webinar information
  - [x] panel `date`
  - [x] panel `title`
  - [x] panel abstract
  - [x] panelist name(s)
  - [ ] panelist email(s)
  - [x] panelist affiliation(s)
  - [x] panelist github id(s)
  - [x] panelist bio(s)
  - [x] moderator name(s)
  - [ ] moderator email(s)
  - [x] moderator affiliation(s)
  - [x] moderator github id(s)
  - [x] moderator bio(s)
- [ ] technical editor checks webinar abstract
- Add panelist(s), moderator(s), and panel to GitHub repo
  - [x] create presenter record(s)
  - [x] create panel record
  - [x] verify content and formatting
- *Update EventBrite*
  - *add full upcoming event*
  - [x] obtain `registration-url`
- [x] Add `registration-url` to panel record in GitHub repo

**Advertising webinar**
- *Update ECP training site*
  - *add full upcoming event*
  - [x] obtain `ecp-abbreviation`
- [x] Add `ecp-abbreviation` to webinar record in GitHub repo
- Update i-p.o site
  - [x] add full upcoming event to <https://ideas-productivity.org/events/strategies-for-working-remotely-panels/>
  - [x] add upcoming event bullet to <https://ideas-productivity.org/events/>
  - [x] add upcoming event bullet to <https://ideas-productivity.org/>
- Add BSSw Event 
  - [x] add event to <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/tree/master/Events>
  - [x] update <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/Site/Announcements/Announcements.md>
  - [x] Publish updates on BSSw.io
  - [x] Notify BSSw Digest team, with link to text formatted for digest
- Prepare and send MailChimp campaign to full audience
  - [x] add audience from most recent panel
  - [x] prepare campaign
  - [x] schedule distribution of email

**Preparing for event**
- Add event metadata
  - [x] `vtc-url`
  - [x] `vtc-session`
  - [ ] `vtc-password`
  - [x] `survey public-url`
- *send connection email*

**Post-event artifact collection**
- [x] obtain panel registration list
- [ ] obtain panel participation list
- [x] obtain slides
- [x] obtain recording(s)
- [ ] obtain additional materials

**Post-event announcement updates**
- Update i-p.o site
  - [ ] remove **upcoming** event from <https://ideas-productivity.org/events/strategies-for-working-remotely-panels/>
  - [x] add **to be archived** past event to <https://ideas-productivity.org/events/strategies-for-working-remotely-panels/>
  - [x] remove **upcoming** event bullet to <https://ideas-productivity.org/events/>
  - [x] add **past** event bullet to <https://ideas-productivity.org/events/>
  - [x] remove **upcoming** event bullet from <https://ideas-productivity.org/>

**Artifact archiving**
- Add archive information to webinar record
  - [x] `archives`

**Webinar followup communications**
- *update ECP training site*
- Update i-p.o site
  - [x] update past event with archives on <https://ideas-productivity.org/events/strategies-for-working-remotely-panels/>
- [x] update <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/swr-panels-cc.md>
  - [x] Publish updates on BSSw.io
- Update MailChimp audience w/ appropriate tag
  - [x] add panel registrants w/ appropriate tag
  - [x] add panel participants w/ appropriate tag
- [x] prepare and send MailChimp campaign to appropriate tag

Note: items in *italics* are usually performed by Ashley.  Items in regular font are usually performed by David.
