### ISSUE TITLE
Panel 009-save the date checklist

### ISSUE THREAD

**Issue by bernhold** [ideas-productivity/remote-work-panels#28]
**Preparing to advertise panel**
- Collect initial webinar information
  - [ ] panel `date`
  - [ ] panel `title`
  - [ ] panel abstract
  - [ ] panelist name(s)
  - [ ] panelist email(s)
  - [ ] panelist affiliation(s)
  - [ ] panelist github id(s)
  - [ ] panelist bio(s)
  - [ ] moderator name(s)
  - [ ] moderator email(s)
  - [ ] moderator affiliation(s)
  - [ ] moderator github id(s)
  - [ ] moderator bio(s)
- [ ] technical editor checks webinar abstract
- Add panelist(s), moderator(s), and panel to GitHub repo
  - [ ] create presenter record(s)
  - [ ] create panel record
  - [ ] verify content and formatting
- *Update EventBrite*
  - *add full upcoming event*
  - [ ] obtain `registration-url`
- [ ] Add `registration-url` to panel record in GitHub repo

**Advertising webinar**
- *Update ECP training site*
  - *add full upcoming event*
  - [ ] obtain `ecp-abbreviation`
- [ ] Add `ecp-abbreviation` to webinar record in GitHub repo
- Update i-p.o site
  - [ ] add full upcoming event to <https://ideas-productivity.org/events/strategies-for-working-remotely-panels/>
  - [ ] add upcoming event bullet to <https://ideas-productivity.org/events/>
  - [ ] add upcoming event bullet to <https://ideas-productivity.org/>
- Add BSSw Event 
  - [ ] add event to <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/tree/master/Events>
  - [ ] update <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/Site/Announcements/Announcements.md>
  - [ ] Publish updates on BSSw.io
  - [ ] Notify BSSw Digest team, with link to text formatted for digest
- Prepare and send MailChimp campaign to full audience
  - [ ] add audience from most recent panel
  - [ ] prepare campaign
  - [ ] schedule distribution of email

**Preparing for event**
- Add event metadata
  - [ ] `vtc-url`
  - [ ] `vtc-session`
  - [ ] `vtc-password`
  - [ ] `survey public-url`
- *send connection email*

**Post-event artifact collection**
- [ ] obtain panel registration list
- [ ] obtain panel participation list
- [ ] obtain slides
- [ ] obtain recording(s)
- [ ] obtain additional materials

**Post-event announcement updates**
- Update i-p.o site
  - [ ] remove **upcoming** event from <https://ideas-productivity.org/events/strategies-for-working-remotely-panels/>
  - [ ] add **to be archived** past event to <https://ideas-productivity.org/events/strategies-for-working-remotely-panels/>
  - [ ] remove **upcoming** event bullet to <https://ideas-productivity.org/events/>
  - [ ] add **past** event bullet to <https://ideas-productivity.org/events/>
  - [ ] remove **upcoming** event bullet from <https://ideas-productivity.org/>

**Artifact archiving**
- Add archive information to webinar record
  - [ ] `archives`

**Webinar followup communications**
- *update ECP training site*
- Update i-p.o site
  - [ ] update past event with archives on <https://ideas-productivity.org/events/strategies-for-working-remotely-panels/>
- [ ] update <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/swr-panels-cc.md>
  - [ ] Publish updates on BSSw.io
- Update MailChimp audience w/ appropriate tag
  - [ ] add panel registrants w/ appropriate tag
  - [ ] add panel participants w/ appropriate tag
- [ ] prepare and send MailChimp campaign to appropriate tag

Note: items in *italics* are usually performed by Ashley.  Items in regular font are usually performed by David.
