### ISSUE TITLE
Panel 012-sustainablehybrid checklist

### ISSUE THREAD

**Issue by bernhold** [ideas-productivity/remote-work-panels#32]
**Preparing to advertise panel**
- Collect initial webinar information
  - [x] panel `date`
  - [x] panel `title`
  - [x] panel abstract
  - [x] panelist name(s)
  - [x] panelist email(s)
  - [x] panelist affiliation(s)
  - [ ] panelist github id(s)
  - [x] panelist bio(s)
  - [x] moderator name(s)
  - [x] moderator email(s)
  - [x] moderator affiliation(s)
  - [x] moderator github id(s)
  - [x] moderator bio(s)
  - [x] `registration-url`
- [ ] technical editor checks webinar abstract
- Add panelist(s), moderator(s), and panel to GitHub repo
  - [x] create presenter record(s)
  - [x] create panel record
  - [x] verify content and formatting

**Advertising webinar**
- *Update ECP training site*
  - *add full upcoming event*
  - [x] obtain `ecp-abbreviation`
- [x] Add `ecp-abbreviation` to webinar record in GitHub repo
- Update i-p.o site
  - [x] add full upcoming event to <https://ideas-productivity.org/events/strategies-for-working-remotely-panels/>
  - [x] add upcoming event bullet to <https://ideas-productivity.org/events/>
  - [x] add upcoming event bullet to <https://ideas-productivity.org/>
- Add BSSw Event 
  - [x] add event to <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/tree/master/Events>
  - [x] Publish updates on BSSw.io
  - [x] Notify BSSw Digest team, with link to text formatted for digest
- Prepare and send MailChimp campaign to full audience
  - [x] add audience from most recent panel
  - [x] prepare campaign
  - [x] schedule distribution of email

**Preparing for event**
- Add event metadata
  - [ ] `survey public-url`

**Post-event artifact collection**
- [ ] obtain panel registration list
- [ ] obtain panel participation list
- [ ] obtain slides
- [ ] obtain recording(s)
- [ ] obtain additional materials

**Post-event announcement updates**
- Update i-p.o site
  - [x] remove **upcoming** event from <https://ideas-productivity.org/events/strategies-for-working-remotely-panels/>
  - [x] add **to be archived** past event to <https://ideas-productivity.org/events/strategies-for-working-remotely-panels/>
  - [x] remove **upcoming** event bullet to <https://ideas-productivity.org/events/>
  - [x] add **past** event bullet to <https://ideas-productivity.org/events/>
  - [x] remove **upcoming** event bullet from <https://ideas-productivity.org/>

**Artifact archiving**
- [x] Add `archives` information to webinar record

**Webinar followup communications**
- *update ECP training site*
- Update i-p.o site
  - [x] update past event with archives on <https://ideas-productivity.org/events/strategies-for-working-remotely-panels/>
  - [x] update <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/swr-panels-cc.md>
  - [x] Publish updates on BSSw.io
- Update MailChimp audience w/ appropriate tag
  - [ ] add panel registrants w/ appropriate tag
  - [ ] add panel participants w/ appropriate tag
- [ ] prepare and send MailChimp campaign to appropriate tag

Note: items in *italics* are usually performed by Ashley.  Items in regular font are usually performed by David.

**Comment by bernhold** [comment]
The SC21 archive will have a finite lifetime.  We should update this and i-p.o when they expire.

**Comment by bernhold** [comment]
SC21 put the recording out on their YouTube channel, and we're now linking to it as an artifact.  We're not going to get any registration/participation info.  Calling this done.
